### ISSUE TITLE
Upgrade to Catlab v0.15?

### ISSUE THREAD

**Issue by sdwfrost** [Merck/ReactiveDynamics.jl#11]
Hi! I've switched over to Catlab v0.15 - is there a timeline to upgrade ReactiveDynamics to this version (which I understand has breaking changes)

**Comment by slwu89** [comment]
Thanks for pointing that out @sdwfrost! We are actually planning a large refactor in the future to incorporate more general tokens (such as a colored Petri net) but I will check the compatibility for the Catlab v0.15 on the current `main` soon. There are a few breaking changes in Catlab v0.15, I think the relevant ones mostly having to do with the return values from `incident`.

**Comment by thevolatilebit** [comment]
In reality, upgrades to Catlab often disrupt the indexing or type conversion process in ReactiveDynamics. Catlab v.0.15 would be no exception, and as Sean suggested, it seems worthwhile to invest our time into a refactor instead. 

Nevertheless, I truly appreciate your interest in this package and hope to maintain it in the future!
