### ISSUE TITLE
Mermaid visualization

### ISSUE THREAD

**Issue by slwu89** [Merck/ReactiveDynamics.jl#8]
It seems possible to use the `graph` keyword (which may just be an alias for `flowchart`, I can't find any docs on `graph`) to make a visualization which would be useful for petri net-like structures. Example here. If it handles moderately-sized nets well, I'll consider implementing this when I familiarize myself with the code.

[![](https://mermaid.ink/img/pako:eNo9jz0LgzAQhv9KuCkBHYybQ6cuhU51NB2CnlUwH6SXgqj_vUlbuj137_PC3Qa9GxAaeATtJ3a9KesrzlshMrCyPDGqEso_UtXNdsSeZmfveczJLnfmZfY4v3y6v0LakewC9u6FYc3-N_B1cmrOb0JAAQaD0fOQztiUZUwBTWhQQZNwwFHHhRQoeyRVR3LtantoKEQsIPpBE55nnR4w0Ix6eeLxBqbnRAQ?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNo9jz0LgzAQhv9KuCkBHYybQ6cuhU51NB2CnlUwH6SXgqj_vUlbuj137_PC3Qa9GxAaeATtJ3a9KesrzlshMrCyPDGqEso_UtXNdsSeZmfveczJLnfmZfY4v3y6v0LakewC9u6FYc3-N_B1cmrOb0JAAQaD0fOQztiUZUwBTWhQQZNwwFHHhRQoeyRVR3LtantoKEQsIPpBE55nnR4w0Ix6eeLxBqbnRAQ)

**Comment by thevolatilebit** [comment]
Let's consider automated visualizations for the refactor.

**Comment by slwu89** [comment]
I agree. If we stick with Catlab we can use Graphviz, if we use AlgAgents or something else, there should be better solutions than Mermaid.
