### ISSUE TITLE
argument error for `Sampler`

### ISSUE THREAD

**Issue by slwu89** [Merck/ReactiveDynamics.jl#9]
When running the simple example below I get the error `ERROR: ArgumentError: Sampler for this object is not defined` that I am having trouble figuring out. The stacktrace is too long to paste here but the last stack frame belonging to ReactiveDynamics is at https://github.com/Merck/ReactiveDynamics.jl/blob/main/src/state.jl#L69, failing inside of the call to `Base.invokelatest`, where `o` is the method `rand`.

I'm on ReactiveDynamics 0.2.5 (master branch).

```julia
using ReactiveDynamics

acs = @ReactionNetwork begin
    1.0, X ⟺ Y, name=>"transition1"
end

@prob_init acs X=10 Y=20
@prob_params acs
@prob_meta acs tspan=250 dt=0.1
prob = @problematize acs

ReactiveDynamics.solve(prob)
```

**Comment by thevolatilebit** [comment]
I see. I am currently refactoring these internals.
